version: '3.8'
services:
  weather_app:
    env_file: "./.env"
    build:
      dockerfile: Dockerfile
      args:
        API_PORT: ${API_PORT}
      context: .
    container_name: weather_app
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      net:
        ipv4_address: 207.8.4.2


  weather_cache:
    image: "redis:alpine"
    container_name: weather_cache
    env_file: "./.env"
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASS} --port ${REDIS_PORT}
    ports:
    - ${REDIS_PORT}:6379
    expose:
    - ${REDIS_PORT}
    volumes:
      - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      net:
        ipv4_address: 207.8.4.5

networks:
  net:
    external:
      name: gmweather_net_dev


